### ISSUE TITLE
Clicking most of the buttons in the menu crashes the browser

### ISSUE THREAD

**Issue by DaVikingMan** [chm46e/sulfer#2]
The following actions cause the browser to crash:
- Clicking the history button
- Clicking the bookmarks button
- Clicking the help button in About section

I also wanted to request a feature for supporting mouse gestures(like ctrl+touchpad/mouse and so on)

**Comment by veisveer** [comment]
Hello!
I tried building it in Pop OS live usb and it seems to work well, no crashes.. (latest garudalinux iso is broken)
Could you possibly run it through ltrace and/or strace and return the latest calls? (valgrind if memory related)

About the feature:
I thought of adding ctrl+mousescroll for zooming, but i'm not sure what other useful shortcuts could be added.
My touchpad barely works in my lfs, so i'm not currently able to test touchpad actions..

**Comment by veisveer** [comment]
Also, could you run it through the terminal as: $ xupric
If there are any errors/warnings, it would be awesome if you'd return em aswell.

**Comment by DaVikingMan** [comment]
I tried it from the terminal and it seemed to be a memory problem, so I ran it with valgrind:
`==22364== HEAP SUMMARY:
==22364==     in use at exit: 6,000,539 bytes in 63,930 blocks
==22364==   total heap usage: 374,304 allocs, 310,374 frees, 45,811,141 bytes allocated
==22364==
==22364== LEAK SUMMARY:
==22364==    definitely lost: 13,459 bytes in 50 blocks
==22364==    indirectly lost: 59,243 bytes in 2,458 blocks
==22364==      possibly lost: 155,718 bytes in 1,884 blocks
==22364==    still reachable: 5,279,798 bytes in 55,678 blocks
==22364==                       of which reachable via heuristic:
==22364==                         multipleinheritance: 3,840 bytes in 13 blocks
==22364==         suppressed: 889 bytes in 1 blocks
==22364== Rerun with --leak-check=full to see details of leaked memory
==22364==
==22364== For lists of detected and suppressed errors, rerun with: -s
==22364== ERROR SUMMARY: 2 errors from 1 contexts (suppressed: 0 from 0)
`

**Comment by DaVikingMan** [comment]
And this is the part of strace where the history button is pressed:
`newfstatat(AT_FDCWD, "/home/hyakki/.cache/xupric/history.db-wal", 0x7fff7fe997e0, 0) = -1 ENOENT (No such file or directory)
newfstatat(13, "", {st_mode=S_IFREG|0600, st_size=8192, ...}, AT_EMPTY_PATH) = 0
fcntl(13, F_SETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=0, l_len=0}) = 0
fcntl(13, F_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=1073741824, l_len=1}) = 0
fcntl(13, F_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=1073741826, l_len=510}) = 0
fcntl(13, F_SETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=1073741824, l_len=1}) = 0
newfstatat(AT_FDCWD, "/home/hyakki/.cache/xupric/history.db-journal", 0x7fff7fe997e0, 0) = -1 ENOENT (No such file or directory)
pread64(13, "\0\0\0e\0\0\0\2\0\0\0\0\0\0\0\0", 16, 24) = 16
newfstatat(AT_FDCWD, "/home/hyakki/.cache/xupric/history.db-wal", 0x7fff7fe997e0, 0) = -1 ENOENT (No such file or directory)
newfstatat(13, "", {st_mode=S_IFREG|0600, st_size=8192, ...}, AT_EMPTY_PATH) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} ---
rt_sigaction(SIGSEGV, {sa_handler=SIG_DFL, sa_mask=~[RTMIN RT_1], sa_flags=SA_RESTORER, sa_restorer=0x7f82ff26b560}, NULL, 8) = 0
rt_sigreturn({mask=[]})                 = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} ---
+++ killed by SIGSEGV (core dumped) +++`

**Comment by veisveer** [comment]
hmm. can't replicate it.
The strace contains a ton of ENOENT(no such file or dir) errors. It seems to try to access (history.db-wal and history.db-journal),
which don't exist in the source. only history.db. maybe it's a <sys/stat.h> thing.

You could try removing xupric's cache folder aka $ rm -r ~/.cache/xupric
Then after have a look, if all the files/folders get generated & the permissions. 
(WebKitCache, cookies, data, history.db, hsts, itp, offline)
Also clone the repo fresh. with a fresh build directory. and try to build.
If it still exists, an ltrace (library call tracer) run might help.

And yes, xupric is pretty bad with memory management currently. I have it in my todo.

**Comment by DaVikingMan** [comment]
After building the latest version, the cookies aren't getting generated. Error:
`PANIC! cookie: failed to get cookies len: no such table: moz_cookies%   `

**Comment by DaVikingMan** [comment]
Also, I don't know if this is expected behavior but cookies are being generated as a file instead of a folder(As in that in the cache folder, cookies is a file instead of a folder)

**Comment by veisveer** [comment]
Yep, my debugging messages seem to pay off:D
Yes, cookies are stored in a sqlite file. In fact, webkit2gtk does not seem to support storing cookies in a directory.
It's easier to manage cookies aswell, if they are just in a single file, rather than scattered around.

Now there are 3 possibilities:
1) Webkit2gtk created a different naming for your cookies table, which isn't "moz_cookies".
Now either just upload the cookies file somewhere and return the link or
return the table name by opening ~/.cache/xupric/cookies with sqlitebrowser (or any other sql browser).
2) Webkit2gtk hasn't created a table at all, which might be caused by not running the browser first with ephemeral = false
3) (unlikely) You accidentally modified the file and added in that % at the end?

**Comment by veisveer** [comment]
You could also run xupric via the terminal with (enables debugging mode):
(if you see any Connection refused messages, then you can safely ignore them)
xupric --debug

**Comment by DaVikingMan** [comment]
I had checked it by running .table in sqlite and it seems like it hasn't created any tables in the file

**Comment by veisveer** [comment]
Okay, I'm getting the exact same error message when I delete my cookies and run the browser with ephemeral true.
Can you try:
* open ~/.config/xupric/xupric.conf
* set ephemeral = false
* run the browser
* after running, you can set it back.

If ephemeral (private browsing mode) was set to true right from the start, then webkit never creates the table.
If that wasn't it, i have no clue why wouldn't webkit create the table??

**Comment by DaVikingMan** [comment]
ephermal is set to false by default

**Comment by DaVikingMan** [comment]
Removing xupric's config file and rebuilding xupric seems to have fixed the problem
