### ISSUE TITLE
The new updates doesn't build properly

### ISSUE THREAD

**Issue by DaVikingMan** [chm46e/sulfer#3]
Error message when trying to build:
`cp: cannot create regular file '/home/<homedir>/.config/xupric/styles/app/': Not a directory
cp: cannot create regular file '/home/<homedir>/.config/xupric/styles/app/': Not a directory
cp: cannot create regular file '/home/<homedir>/.config/xupric/styles/app/': Not a directory
[2/2] Generating before_build with a custom command
ninja: build stopped: subcommand failed.
`

**Comment by veisveer** [comment]
oh yea, I fixed the bug in my local repo, but forgot to commit it.
I'll commit it right away.
